### ISSUE TITLE
A4 Elevation Download

### ISSUE THREAD

**Issue by CNTSCGIS** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#1]
Did not work when Request Extent was selected or Site Define AOI.
The error message said the selected CLU layer is not from the Determinations project folder. Exiting.
Did work with Site CLU.
Did work when the elevation service does not cover the entire extent of the Tract.

![image](https://user-images.githubusercontent.com/63863189/119194490-c4607700-ba48-11eb-91af-2424a34bdb39.png)
![image](https://user-images.githubusercontent.com/63863189/119194516-ce827580-ba48-11eb-88ac-76244686ee27.png)

**Comment by CEM-NRCS** [comment]
Note that the header for Tool 4 requests the Site CLU in the first dropdown. Your screenshot shows you had the Request Extent selected.
