### ISSUE TITLE
Tool D14 - Warning

### ISSUE THREAD

**Issue by MelHann213** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#10]
Tool runs with "completed with warnings." message. Package created in 4.0.5. Tool runs fine 
![D14_warning](https://user-images.githubusercontent.com/43419575/122260935-d562a380-cea1-11eb-8e3c-f1bb1cdd6b1b.png)
but just an FYI.

**Comment by DeePederson** [comment]
I got an error when running this tool.

package 'xlsx' was built under R version 4.0.5
 package 'knitr' was built under R version 4.0.5
 package 'flextable' was built under R version 4.0.5
 package 'textreadr' was built under R version 4.0.5
 Error in format_sci : values must be length 1, but FUN(X[[1]]) result is length 0
 	Failed to execute (Create026WC).

**Comment by gahisu** [comment]
Tool fails and does not complete the 026 form.
![Step_14_Error](https://user-images.githubusercontent.com/66690345/122928589-a334c400-d32f-11eb-9c9a-bfaad5a2bad1.jpg)

**Comment by CEM-NRCS** [comment]
Closing issue in response to original post about Warnings. Subsequent posts for an error with this tool have been moved to a new issue here:
[https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/issues/23](url)
