### ISSUE TITLE
B. Reference Data 02. Create Elevation Derivatives

### ISSUE THREAD

**Issue by tyler-witkowski** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#106]
Code references different map than included with the zipped tool folder. Located at line 72. Changed to 'Determinations' to correct local copy and it worked as intended.
![WCTool_mapref](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/assets/154430432/aa72a158-c160-49cd-8755-6dc897dee5bd)

**Comment by dylan-harwell-usda** [comment]
Fixed
