### ISSUE TITLE
B.03, C.03, and D.04:  Tool Failure when PLSS == True....Tool Success when PLSS == False

### ISSUE THREAD

**Issue by AC0192021** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#107]
I have 3 users attempting to run WC Tool B.03, C.03, D.04, using the PLSS option, and all experience tool failure.  Error message is highly correlated with code querying BLM layers.  This occurs in both ArcGIS Pro 2.9. and 3.1.3 and only when the PLSS option ==True.  When PLSS == False, B.03, C.03, and D.04 run to completion and as expected.  All users migrated to ArcGIS Pro 3.1.3 and WC Tool version 2.0.3 and the issue persists.  To my knowledge, at this one user in Illinois NRCS experienced the same.
![WC Tool_Export Maps_PLSS Error_2](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/assets/87500821/53a7a5bc-ed4c-4a72-845b-4271ab6b2278)
![WC Tool_Export Maps_PLSS Error_1](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/assets/87500821/f0f41d14-76c8-4e1f-852f-d86d833693df)

**Comment by dylan-harwell-usda** [comment]
Hi @AC0192021, I just checked a couple things, 1) the BLM services appear to be online and live, I also ran the PLSS query from my PC and it ran successfully. So the error is coming from `urllib urlopen()` function. Are you connected to any VPN when running the tool? Are all users experiencing the error connected to the same network? Can you open the BLM service urls from a browser?
https://gis.blm.gov/arcgis/rest/services/Cadastral/BLM_Natl_PLSS_CadNSDI/MapServer/1
https://gis.blm.gov/arcgis/rest/services/Cadastral/BLM_Natl_PLSS_CadNSDI/MapServer/2

**Comment by AC0192021** [comment]
All 3 users are experiencing this while in office and on separate local networks.  When teleworking, 1 user is experiencing this with or without VPN.

BLM links:  1 user was successful in Edge, 1 user successful in Chrome, and the last user was not successful in either Edge or Chrome.

I can't duplicate this in any version of the WC Tool or ArcGIS Pro and have zero reports of these issues from the other 15 users.
