### ISSUE TITLE
A o3. Define Request Extent

### ISSUE THREAD

**Issue by DeePederson** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#11]
Need to add specific instructions for using the split tool prior to running this tool. This applies to many of our requests where portions of existing fields are requested. After splitting the desired field, the user would select parameters in #2 below when running the tool. I tried using #3 to accomplish this, but it creates a new polygon instead of splitting existing fields. 

I already mentioned this to the developers - adding it here so it doesn't get lost.

**Comment by CEM-NRCS** [comment]
Got it Dee. We'll be sure that it's improved in future Help files and documentation and completely clear in the full release documentation.
