### ISSUE TITLE
Create form from Site CLU CWD

### ISSUE THREAD

**Issue by jessegray2** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#110]
Is there a way to create the form from the Site CLU CWD layer instead of the Site CWD layer? If the CLU CWD layer is used for the determination map it will not match the form using the CWD layer.

**Comment by dylan-harwell-usda** [comment]
Have to defer to @CEM-NRCS  on this one.

**Comment by CEM-NRCS** [comment]
The form is actually built from hidden tables that are generated when the _D03. Create CWD Map Layers_ tool is run. If the results don't seem correct, double check the mapping/attributing and then make sure to run the Validate tool followed by the Create CWD Map Layers tool before making maps or using Create Forms and Letters.

The selection of Site CWD layer in the Create Forms and Letters tool is simply to help the tool deconstruct the path to the current determination's project folder and work with the data in that folder.

**Comment by dylan-harwell-usda** [comment]
@jessegray2, @CEM-NRCS  Is this still an issue or should it be closed?

**Comment by jessegray2** [comment]
No, it can be closed.
Thanks,
Jesse
