### ISSUE TITLE
Extract CLU failing for certain tracts

### ISSUE THREAD

**Issue by dylan-harwell-usda** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#111]
Issue first reported by: @jessegray2

Create Project tool is failing in the extract_CLU_by_tract script for some tracts, but not all. I was able to reproduce the error for Tracts in Georgia, as well as Colorado during my testing. Tracts in Indiana worked successfully.

![MicrosoftTeams-image](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/assets/120053864/86c2cd9d-79d5-4e8d-abcb-e95d46a2186a)

**Comment by dylan-harwell-usda** [comment]
![image](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/assets/120053864/f8725a75-d4ca-48b7-944a-3274838dad8f)

**Comment by gahisu** [comment]
We are having this issue in Iowa as well.

**Comment by dylan-harwell-usda** [comment]
CLU service reported to be updated and extract_CLU_by_tract functionality restored.
