### ISSUE TITLE
Tool B. 08. - Validate Sampling Units

### ISSUE THREAD

**Issue by gahisu** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#12]
When validation fails due to missing attributes, the Site_Sampling_Unit cannot be edited due to a file lock. A work-around is to remove the layer from the Contents and then re-add using the Undo last action button; the layer can then be edited.

**Comment by CEM-NRCS** [comment]
Another workaround is to close the map frame and reopen it from the catalog pane without removing/undoing removal of layers. Does this alternate workaround method work for you instead/as well?

**Comment by JeffSoil** [comment]
I had the same issue where I was unable to edit the sampling unit shapefile. Closing the map frame and reopening it did work for me.

**Comment by christinaripplinger** [comment]
This does not work for me. It tells me there is at least one sampling unit does not have a sampling unit number assigned. However, it will not allow me to edit any sample units.

**Comment by CEM-NRCS** [comment]
Identified the issue to be related to attribute rules and layer management during processing. Made revisions to reduce instances of this happening.
