### ISSUE TITLE
Tool 14 Create Forms and Letters

### ISSUE THREAD

**Issue by TimPrescott** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#14]

**Comment by TimPrescott** [comment]
After uninstalling and reinstalling R Studio and R for Windows, deleting and reinstalling the WC tools for Pro, and running the LibraryInstall.R script, I get the following error messages in RStudio.

![r6_error](https://user-images.githubusercontent.com/86414673/123270268-61d61d00-d4c5-11eb-82bf-0de6cb991978.png)
![r7_error](https://user-images.githubusercontent.com/86414673/123272547-761b1980-d4c7-11eb-8ba8-8d912090fed4.png)
![r8_error](https://user-images.githubusercontent.com/86414673/123272558-77e4dd00-d4c7-11eb-8099-05818c569890.png)

**Comment by OHSSS** [comment]
I am getting a similar message:
annot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/src/contrib:
  cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES'package 'xlsx' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packagescannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0:
  cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES'
 cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/src/contrib:
  cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES'package 'rmarkdown' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packagescannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0:
  cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES'
 cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/src/contrib:
  cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES'package 'knitr' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packagescannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0:
  cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES'
 cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/src/contrib:
  cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES'package 'flextable' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packagescannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0:
  cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES'
 cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/src/contrib:
  cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES'package 'textreadr' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packagescannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0:
  cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES'
 there is no package called 'xlsx'
 there is no package called 'rmarkdown'
 there is no package called 'knitr'
 there is no package called 'flextable'
 there is no package called 'textreadr'
 Error in doWithOneRestart : there is no package called 'rmarkdown'
 Failed to execute (Create026WC).


Then I saw this from Berkeley
CRAN mirror restricted to UC Berkeley
The CRAN mirror at UC Berkeley's College of Natural Resources is no longer available to off campus users and has been removed from the CRAN mirror list. The load on our server was too much.

Berkeley folks can continue to access the mirror from on-campus networks or from within the VPN.

The rest of the R community: Sorry, but you'll have to please choose a different CRAN mirror.

**Comment by KB-TNCC** [comment]
I'm getting the same message, is there a fix? 

 cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/src/contrib:
  cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES'package 'xlsx' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packagescannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0:
  cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES'
 cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/src/contrib:
  cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES'package 'rmarkdown' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packagescannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0:
  cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES'
 cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/src/contrib:
  cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES'package 'knitr' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packagescannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0:
  cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES'
 cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/src/contrib:
  cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES'package 'flextable' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packagescannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0:
  cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES'
 cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/src/contrib:
  cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES'package 'textreadr' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packagescannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0:
  cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.0/PACKAGES'
 there is no package called 'xlsx'
 there is no package called 'rmarkdown'
 there is no package called 'knitr'
 there is no package called 'flextable'
 there is no package called 'textreadr'
 Error in doWithOneRestart : there is no package called 'rmarkdown'
 Failed to execute (Create026WC).

**Comment by CEM-NRCS** [comment]
Updating install instructions for test number two. Closing this issue for test number one.
