### ISSUE TITLE
14. Create Forms and Letters

### ISSUE THREAD

**Issue by rcapezza** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#15]
Getting "Access is Denied" error message along with R error when running No. 14 tool.  I have uninstalled and reinstalled the arcgisbinding package a few times without any issues in RStudio, however No. 14 tool still fails.    Verified using ArcGIS Pro 2.6.3 version.

![R_error](https://user-images.githubusercontent.com/86432968/123320081-e7be8c00-d4f6-11eb-869e-7bd25d35e40e.jpg)

**Comment by CEM-NRCS** [comment]
Duplicate issue. Closing this issue.
See ongoing work here: [https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/issues/21](url)
