### ISSUE TITLE
Installation step 10.d

### ISSUE THREAD

**Issue by Calixte2614** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#16]
I receive error message attached when trying to install R-ArcGIS Support.  Any solutions?
Thanks
![step10_d](https://user-images.githubusercontent.com/86480384/123450052-4729a400-d5aa-11eb-9af7-d74487963d97.JPG)

**Comment by CEM-NRCS** [comment]
Interesting. What version of ArcGIS Pro do you have JP?

**Comment by Calixte2614** [comment]
Chris:

Upgrading to Pro 2.7.3 helped get past installation of R studio.

Thanks,

***@***.***D76E8C.C4E815A0]__________________________

Jean-Paul Calixte
GIS/GPS Coordinator
State Geodata Administrator
***@***.***D76E8D.1FBDB750] ***@***.***
***@***.***D76E8D.1FBDB750] 4500 NW 27th Avenue, Bldg. A
    Gainesville, FL 32606
***@***.***D76E8D.1FBDB750] (352) 338-9511
***@***.***D76E8D.1FBDB750] (352) 338-9578

**Comment by CEM-NRCS** [comment]
User had a version below 2.6.3 before upgrade. Upgrade resolved the problem.
