### ISSUE TITLE
Tool A.05 - Create Reference Data - Test Session 3.e. 1 thru 4.  

### ISSUE THREAD

**Issue by japitts8816** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#17]
This maybe a PICNIC and not an issue.  

Test Session 3 e, Test #'s 1-4  - **Creating Reference data** with SSURGO not producing products/map layers/data to the Referenced Extent or Full Tract, but instead creating products/map layers/data to the _Downloaded DEM_  boundary.  The exception of Test Session 3e, was Test #4 - the elevation products.  The elevation products/map layers/data were created to a buffer around the Reference Extent polygon.  With the all Reference and SSURGO data products, it's clipping and creating from the _Downloaded DEM_ boundary instead of the referenced extent.   With elevation products, it's clipping to a buffer around the Referenced Extent, as I "assume" it's supposed to do.

**Comment by CEM-NRCS** [comment]
SSURGO data will always download in a box around the tract. Elevation data will buffer around either the selected choice of tract or request extent. We will add better documentation on this to the help files and supporting documents prior to release. We may also split the tools for SSURGO and elevation into separate tools prior to release.
