### ISSUE TITLE
Tool A 0.1.ii - CLU error on new project

### ISSUE THREAD

**Issue by DMillerAK** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#18]
I get the following error when I click Run when starting a new project.  This error (screenshot below) might also be tied to our Alaska CLU layers.  I have been having issues with the HEL running on our CLU without an intersect/attribute update to the countyCD to county/borough FIPS code.  For the HEL tool to run I have to update the CLU attribute (CountyCD).  However this particular Tract number does run in the HEL tool using a local CLU,

I loaded the CLU from a local version in my Pro project. What CLU does this wetland tool pull from? F drive, web service, etc? 
![image](https://user-images.githubusercontent.com/86498435/123487542-924bb300-d5ba-11eb-8a7a-ff84734be411.png)

**Comment by DMillerAK** [comment]
More info - The CLU feature service countyCD and adminCD are tied to the CLU shapefile number. This is how we get the raw CLU data/attributes from FSA.  However if you look under the county_ansi it does have the correct FIPS code for the area.  The series of screenshots here are the entire attribute for this particular CLU field.

Thought it might help explain part of the situation. 
![image](https://user-images.githubusercontent.com/86498435/123488907-5f56ee80-d5bd-11eb-8706-af99896cf10c.png)
![image](https://user-images.githubusercontent.com/86498435/123488927-6aaa1a00-d5bd-11eb-8ffb-f3017668a2a9.png)
![image](https://user-images.githubusercontent.com/86498435/123488939-739aeb80-d5bd-11eb-811a-9f8a43870d6b.png)

**Comment by CEM-NRCS** [comment]
Updated tool for next test to account for Alaska's unique CLU characteristics.
