### ISSUE TITLE
Sampling Validation Error Message

### ISSUE THREAD

**Issue by japitts8816** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#19]
IDK why I'm getting this error when all my Site Sampling Units have numbers associated with them.  
![Sampling_Validation1](https://user-images.githubusercontent.com/63659670/123690479-0a63e400-d81a-11eb-9a51-9ac667e0df92.JPG)

**Comment by CEM-NRCS** [comment]
Julie, just to confirm, every mapped Sampling Unit looks something like this when it comes to its attributes (individual numbers may vary). In particular, the Sampling Unit number field is populated for each one (note, check the attribute table for any tiny slivers perhaps?).
![image](https://user-images.githubusercontent.com/47194402/123701183-84eb2e80-d82f-11eb-938b-6a02b68a8b42.png)

**Comment by japitts8816** [comment]
Thanks Chris!  I do appreciate YOU very much.  But I foresee alot of our requests being thrown back to FSA for them to include historical lands associated with Farm/Tract, they no longer digitize because it's NOT an Ag field.  ALOT of them being sent back to FSA for FSA to reconcile the CLU field/tract boundaries.  Otherwise, NRCS won't be able to run WCT.  Case in point the little field screen shot I sent you.

Oh well, guess the National folks will come up with something.  I'm just testing tools.  Giving my best shot.

Got another error message on Validating - will put in GitHub.


Julie A. Pitts, GIS Specialist

USDA Natural Resources Conservation Service

Mississippi

Office 601-768-3077

Cell  601-685-8168



Sapiens qui prospicit

     (Wise is he that looks ahead)



“Ability is what you are capable of doing. Motivation determines what you do.  Attitude determines how well you do it”

________________________________

**Comment by OHSSS** [comment]
![sampling unit](https://user-images.githubusercontent.com/87037531/124799160-3f5eed80-df22-11eb-87ee-5012e9f11ec0.png)
I had an issue when we had a sampling unit as 1a, 1b, 1c, (all same sampling unit in different areas)

**Comment by CEM-NRCS** [comment]
This error message/crash is a known error in the test version set to close on July 7th. It's been corrected in the new version that will be released in the second round of testing.
