### ISSUE TITLE
A05  Resource Layers

### ISSUE THREAD

**Issue by CNTSCGIS** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#2]
Soils data worked good.

DEM derivatives did not.  The extracted DEM does not have a coordinate system defined.

![image](https://user-images.githubusercontent.com/63863189/119195691-a98f0200-ba4a-11eb-92fe-61a6b179abdc.png)

**Comment by CNTSCGIS** [comment]
Why color the Flood Freq, NONE rating RED?

**Comment by CNTSCGIS** [comment]
Completed Toolset A.

**Comment by TimPrescott** [comment]
I got the same message this morning running tool 05. Create Reference Data.
![tool_05_error](https://user-images.githubusercontent.com/86414673/123458046-32e5a700-d5aa-11eb-8cd7-70d3256b60cd.png)

**Comment by CEM-NRCS** [comment]
Latest released version should address this as long as the "Determinations" map frame of the active project has a WGS 1984 UTM Zone (x) projected coordinate system set. This error can re-appear if the map frame ("Determinations") is not in a projected coordinate system before starting tool A.01 to "set" the project site's coordinate system.

**Comment by CEM-NRCS** [comment]
Added an error check/trap catch to the Create New Project tool to confirm the map frame in use has a projected coordinate system because the map frame later drives subsequent data creation steps in other tools, including A05.
