### ISSUE TITLE
ValidatesSU error message 

### ISSUE THREAD

**Issue by japitts8816** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#20]
Validate Sampling Units - Line 614 in <module>.  Guess I tore it up??  I hope not.

**Comment by japitts8816** [comment]
Sorry - hit enter before I was finished.  IDK what caused this issue, and I couldn't figure it out.  Line 614 of the module.  
![validateSU](https://user-images.githubusercontent.com/63659670/123703171-a34e2b80-d829-11eb-9866-92e48212ab09.JPG)

**Comment by CEM-NRCS** [comment]
This is a valid code bug. Will post a fix in the next version.
