### ISSUE TITLE
Tool A05 Add Layer to Map Error in getSSURGO_WCT_ArcGISPro.py

### ISSUE THREAD

**Issue by KsmileyTN** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#22]
Could not create SSURGO layers. Tried scenarios 1-3. When trying 4, had no problem generating elevation layers. Below is the message when I tried to make the SSURGO layers. Perhaps it is having trouble adding the layers to the map. I have Pro 2.7

![A05 request extent with all interps](https://user-images.githubusercontent.com/87093085/124814483-aaf98880-df2b-11eb-9363-509909df767c.JPG)

**Comment by ajdiazdk** [comment]
# Updated  7/9/2021 - Adolfo Diaz
# - Addressed a bug that occurred while adding the symbolized layers to ArcGIS Pro.
#   Updated the map reference object to "aprxMap" when the 'SSURGO Layer' group does NOT exist.
#   Prior to this update, the 'map' object that was being referenced came from the first attempt
#   at determining whether the 'SSURGO Layer' group layer existed.  That 'map' object is now deleted.
