### ISSUE TITLE
Step 10 d

### ISSUE THREAD

**Issue by jeff-ARSS** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#24]
![Capture](https://user-images.githubusercontent.com/87143736/124963250-2ec37b80-dfe5-11eb-91b0-fd9702326508.PNG)

I have this error code.  Saw a similar post and upgraded Pro to 2.7.0 which was the newest I have and still could not make it work.

**Comment by CEM-NRCS** [comment]
Possible solution is to delete the folder specified in the error for removal.
Updating install instructions for test number two. Closing this issue for test number one.
