### ISSUE TITLE
A01 v

### ISSUE THREAD

**Issue by DGehring-KY** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#25]
The first time using this when no folder called C:\Determinations exists, the program creates the folder, but in this step, we are supposed to save the APRX file into the folder it created under the C:\Determination folder for this county/tract/date. AcrGIS Pro does not see this folder when I go to "Save As..." as it just created this new folder path, and it needs to close and reopen before it is visible to ArcGIS Pro. I had to save the file elsewhere and move it to the suggested folder. This then messed up some of the links in the project which needed fixing.

When I ran this on a second tract, again it could not find the new folder just created (county/tract/date) as it was just created but ArcGIS Pro and was not visible when I went to "Save As..".  The program needs to refresh itself somehow so that it can see the new path that it just created.

Here is a screen shot of my ArcGIS and Windows Explorer showing how the new folder is shown in Windows Explorer, but not in ArcGIS Pro.  (Using ArcGIS Pro 7.3).
[A01_v.docx](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/files/6786643/A01_v.docx)

**Comment by CEM-NRCS** [comment]
Click the refresh button in the browse window for Save As.

**Comment by DGehring-KY** [comment]
That does not work.  The Refresh option is greyed out.

**Comment by CEM-NRCS** [comment]
I added some notes to the instructions document to highlight the level above the expected new content and then click Refresh. Does that work?

**Comment by DGehring-KY** [comment]
Nope. The Refresh option is always greyed out no matter what level I am on in the file system.

**Comment by CEM-NRCS** [comment]
Just to be sure, we're talking about this button inside the Save Project As dialogue - 
![image](https://user-images.githubusercontent.com/47194402/124988782-701b5180-e00c-11eb-9b80-f0de2c4ef226.png)
