### ISSUE TITLE
One Drive

### ISSUE THREAD

**Issue by DGehring-KY** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#28]
I have been converted over to One Drive (for my H drive), and I don't know what is all being downloaded, saved, or deleted, but this testing has caused my OneDrive to constantly try to delete files and it says that it cannot delete them. It really gets annoying fast with the notification popping up every 10-20 seconds. One Drive says that I can stop the sync, but I wanted to inform you that in the near future, everyone is going to this One Drive and will be frustrating for them as well. I ma not sure if background processes can be run on the C Drive and not on server related drives?

**Comment by CEM-NRCS** [comment]
A lot of other testers have been converted to this as well and are not reporting the same issue.

What is the install location for the folder of this tool that you have used on your system? This folder should not be installed into the Documents directory.

Have you marked the install folder for sync by OneDrive (OneDrive can be configured to sync any folder of the user's choosing on their system). If it happens to be marked for syncing, then it should be unchecked.

Do you have a C:\Determinations folder yet, either via creation or from the tool? If so, make sure it is also not marked for syncing in the OneDrive settings.

Are you using the provided starting template for the tool, or did you create a template from scratch?

If you've created or modified a starting template, where are you saving it?

For the ArcGIS Pro project with the tools - if you go to Project --> Options --> Current Settings, do you see the following:
![image](https://user-images.githubusercontent.com/47194402/125290190-09d54e00-e2ee-11eb-9da8-05d7083b92e1.png)

For any ArcGIS Pro project, if you go to Project --> Options --> General --> Create Projects, what do you see in the Geodatabase entry?

Are you able to determine whether R or the arcgisbinding for R got installed in your Documents folder?

**Comment by DGehring-KY** [comment]
IT determined that R did not fully install correctly from Software Center and they had to do a Check Disk on it to repair the missing parts of the install. Once the Check Disk ran, it corrected the issue and I have not had an issue with it since.
