### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by KGsoils** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#3]
I followed directions but the winzip made an extra folder.
[winzip.docx](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/files/6554735/winzip.docx)

It created the folder Welland-Toos----ArcGIS-Pro-master

**Comment by CEM-NRCS** [comment]
For now, rename and re-arrange the folders downloaded, as needed. I'll work on making the install directory independent. We have a promising development on that front.

**Comment by CEM-NRCS** [comment]
Kevin, how is the new zip file from the Tool Testing Teams page working for this?

**Comment by CEM-NRCS** [comment]
Working to make the install directory independent in the next test version (e.g., can put the downloaded folder anywhere).
Also will update and improve the install instructions to account for feedback from test one.
