### ISSUE TITLE
Tool A.01. completed with warnings

### ISSUE THREAD

**Issue by lmblackburn** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#33]
![image](https://user-images.githubusercontent.com/87446239/125681306-36af4549-8d10-4f09-a868-b2d74d97ee2f.png)
FYI - folder created was not as described in the testing document, day was not part of folder name.

appears to be a discrepancy in projections

**Comment by CEM-NRCS** [comment]
These warning messages are normal for the extract CLU tool adopted for use within this tool. Outputs are as expected, despite the warning. Day has been dropped from folder naming. Documentation will be updated to reflect this.
