### ISSUE TITLE
Tool A. 04. Download Elevation

### ISSUE THREAD

**Issue by af063402** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#35]
I can't use this tool, because it states in the error "The table already exists".  I created a new project and ran through the steps again only to get the same error.

[Tool A. 04 Download Elevation.docx](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/files/6825641/Tool.A.04.Download.Elevation.docx)
![A04_Error](https://user-images.githubusercontent.com/87497399/125842875-24f2dd6f-f7d1-4ffa-984b-9c21900e5270.JPG)

**Comment by CEM-NRCS** [comment]
Updated the troubleshooting section of the user guide to address this error.
