### ISSUE TITLE
D15  Create Letter and Form

### ISSUE THREAD

**Issue by CNTSCGIS** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#4]
All tools that are ready to test have ran successfully.  Except this D15.  Cannot find the path.  
R has been installed.

![image](https://user-images.githubusercontent.com/63863189/119852922-5814c600-bed5-11eb-8fd6-7b45c342b096.png)

**Comment by CEM-NRCS** [comment]
Use R Studio to remove existing arcgisbinding install. After removal, confirm "arcgisbinding" was deleted from the old R library (typically at Documents\R\win-library\<version number>\. Use R Studio (per the training guide) to type the command to install arcgisbinding again. Then try the tool again.

**Comment by CEM-NRCS** [comment]
For testers, Dwain has posted a video of how to correct the issue, here.
https://usdagcc.sharepoint.com/sites/FPAC-NRCS-NationalWetlandTool-ToolTesting/Shared%20Documents/Tool%20Testing/NOW%20TESTING%20_TEST1/WCTool_RSupport_2021_06_02.mp4
