### ISSUE TITLE
Step 8 Error

### ISSUE THREAD

**Issue by soilmanjeff** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#40]
![image](https://user-images.githubusercontent.com/87660092/126356995-deda5fdb-eb04-4fc6-a571-05a8ed98eb74.png)

File "C:\GIS_Tools\NRCS_Wetland_Tools_Pro\SUPPORT\Validate_Sampling_Units.py", line 614, in <module>
    cur_su = str(su_row[1] + su_row[2])

	TypeError: unsupported operand type(s) for +: 'int' and 'str'
 Failed to execute (ValidateSU).

**Comment by CEM-NRCS** [comment]
Code was updated to correct this bug prior to full release.
