### ISSUE TITLE
Testing 2 issue with R script

### ISSUE THREAD

**Issue by CNTSCGIS** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#41]
Error in remove.packages(arcgisbinding)
object 'arcgisbinding' not found
<img width="255" alt="Rscript issue" src="https://user-images.githubusercontent.com/63863189/127508473-1ae99097-246e-432f-871e-276b322ce46b.png">

**Comment by DGehring-KY** [comment]
I get the same exact error message when I tried to remove arcgisbinding
![image](https://user-images.githubusercontent.com/87146957/127669744-42136ad6-f183-4e06-9ceb-09348c38307b.png)
