### ISSUE TITLE
Test2 A6 scenario 3

### ISSUE THREAD

**Issue by DGehring-KY** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#43]
After running scenario 3, which ran correctly, the digitizing layer remains in the PLLS choice window and creates an error the next time you try to run the tool.  There needs to be instructions to remove this or change to another layer since the digitizing layer is no longer available after this tool has ran.

![image](https://user-images.githubusercontent.com/87146957/127702416-610e79e6-80a1-45dc-9897-48c015252889.png)

**Comment by MatthewBaltes** [comment]
I ran into this as well.  If it could clear itself, or remain active, that might do the trick. The map creation worked well and fast. That's a game changer.

**Comment by CEM-NRCS** [comment]
Digitizing layer now removed at end of execution so that re-runs work as normal.
