### ISSUE TITLE
Test2 D14

### ISSUE THREAD

**Issue by DGehring-KY** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#47]
This is a little different than Test1, where the output is all in Word. This is nice and much easier to modify as needed. 

Everything appears to be on the form and letter correctly, except the request date on the CPA-026 is in a format that is hard to read (Year-Month-Day), unlike the date at the signature line that is Month-Day-Year.  Can the request date be in the same format as the signature date (actual day of week is not required (Friday))?

**Comment by CEM-NRCS** [comment]
Request date and signature date are both now mm/dd/yyyy
