### ISSUE TITLE
Test2 A06 not creating maps

### ISSUE THREAD

**Issue by japitts8816** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#48]
I really don't think this is an error.  I think it's because I picked different maps to create (individual *.pdf's) for a few soils layers that I did NOT create when going through previous tool.  I think it's just telling me, "Hey YOU!  You didn't create those map layers, therefore I can't create the *.pdf maps.  Go back and create the SSURGO layers and I'll create the map products."  I mean, I think that's what it's doing.  Slapping the head of the PICNIC, apparently.  LOL!  
![Tool A06](https://user-images.githubusercontent.com/63659670/128259686-09f8187f-aa95-4ffc-8b7d-de36df3f1e23.JPG)

**Comment by lmblackburn** [comment]
I didn't have much luck w/ this tool either.  I tried a few different variations with selecting just one map or more, still no luck.
![image](https://user-images.githubusercontent.com/87446239/128929541-ea8b0dcc-ee5d-49dd-a7ee-64c193d4ea4b.png)
Here's the message from another run:  BTW - West Virginia doesn't have the PLSS system...and I chose not to check that box...but that error is popping up.
```
Verifying inputs...
Setting variables...
Commence logging...
Managing output file names...
Either **the Show Location parameter was not enabled or the PLSS query failed.**
A Town, Range, Section text box will not be shown on the output map(s).
Collecting header information from project table...
Updating layout elements...
Updating Layout Information...
Updating Layout Information...
Updating Layout Information...
Updating Layout Information...
Preparing map layers for display...
Creating the Site Map PDF file...
Failed script 06. [Optional] Export Reference Maps...
Traceback (most recent call last):
  File "C:\GIS_Tools\NRCS_Wetland_Tools_Pro\SUPPORT\Export_Reference_Maps.py", line 762, in <module>
    lyr = m.listLayers(zoomLyr)[0]
IndexError: list index out of range
Failed to execute (ExportReferenceMaps).
Failed at Tuesday, August 10, 2021 4:21:09 PM (Elapsed Time: 2.06 seconds)
```

**Comment by CEM-NRCS** [comment]
This is due to the SSURGO layers being part of a group. Procedures were changed to recommend using the Site_CLU layer when using the zoom to a layer option.
