### ISSUE TITLE
Test 2 manual 

### ISSUE THREAD

**Issue by jeff-ARSS** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#51]
Manual has D.14 as Create forms and letters, the tool has 14 as (Optional) Export Previous Det map. So in the tool I ran 15 Create Forms and letters a got this error:
![Capture](https://user-images.githubusercontent.com/87143736/128413410-5dbef35c-30cc-4429-8b5f-b54f471465b4.PNG)

**Comment by DMillerAK** [comment]
Another item for manual document updates:

- page 7 under 7.A. v - AOI is misspelled as AIO (last one highlighted in this screenclip)
- 
![image](https://user-images.githubusercontent.com/86498435/129276253-7929e7e0-6bf9-42bf-a614-f43d6098b469.png)
