### ISSUE TITLE
Test 2 14 (15)

### ISSUE THREAD

**Issue by MatthewBaltes** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#52]
I was unable to run this. Received the following error. Maybe I messed something up at the beginning with the R package.
![image](https://user-images.githubusercontent.com/88503273/128531523-0e863c70-b4e0-44fc-8492-c406c608a8d6.png)

**Comment by MatthewBaltes** [comment]
I am on version 2.7.3

**Comment by coguariglia** [comment]
I get the same error.  I also had some of the issues noted by others related to R Install instructions in Appendix D.

**Comment by DMillerAK** [comment]
Similar situation here but my error says script was built in 4.0.5. My R is at version 4.0.3.
![image](https://user-images.githubusercontent.com/86498435/129275963-e084a581-5b11-47b4-bf2c-ec715271c2c3.png)
![image](https://user-images.githubusercontent.com/86498435/129276010-ca388b59-ba2d-4dbc-a4e7-101c0a9705de.png)

**Comment by AC0192021** [comment]
Same as DMillerAK
