### ISSUE TITLE
Test 2 B9 Labels

### ISSUE THREAD

**Issue by coguariglia** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#53]
Our current Base Maps show the SU boundary but only the ROP label with the associated Y or N so it is easier to read.  This example shows how difficult it can be to read with the SU label and ROP label.  We also don't show acres in the label on our Base Map.  I can turn the SU labels off in Adobe but then the there is no Y or N associated with the ROP.  Can we enter Y/N for ROP instead of the SU and then only include the ROP labels?  There are also labels that do not show up on this map because of overlapping issues.  I tried changing font size, but still can't get all of them to appear even when set to 6 pt. The ROP # with just a Y or N would help solve this issue too.

![image](https://user-images.githubusercontent.com/84814344/128535059-89944bb6-e546-403c-a994-cb7a760347ca.png)

**Comment by CEM-NRCS** [comment]
Use annotation functions to convert labels to annotation and move them, use leader lines, etc... Full cartography for complex scenarios cannot be completely automated.
