### ISSUE TITLE
Disable Editing Question

### ISSUE THREAD

**Issue by coguariglia** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#54]
This isn't an issue with the tool, but a question about the ability to stop editing.  I have the option to enable editing and disable editing in my Edit tab.  The icon for disabling is a square next to the pencil so I assumed it was the same as stop editing.  I have used it quite often and it gives the option to save all edits before disabling.  I noticed that the instructions often state that there is no "stop editing" in ArcGIS Pro.  I haven't had any issues that I know of and it seems to correct any editing issues without removing layers or closing and opening the project.  I just disable, save edits, and enable again.  Is is ok to use this option or is there a reason to avoid using disable editing?

**Comment by CEM-NRCS** [comment]
The button you describe is effectively a Stop Editing button. It can be enabled as an option in Pro, but it would perhaps be better for user guides to state that editing does not have a start/stop button by default, the way ArcMap did.
