### ISSUE TITLE
Tool D. 15 error

### ISSUE THREAD

**Issue by af063402** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#55]
https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro

**Comment by DMillerAK** [comment]
This is the error I got when I tried running Tool 15 - Create Forms/Letters.  Note my R version is 4.0.3 (as stated in the Appendix D). If you have questions - just let me know.
![image](https://user-images.githubusercontent.com/86498435/129275570-2024f01d-c5f2-43d3-ab4d-7d7f2eaa619a.png)
![image](https://user-images.githubusercontent.com/86498435/129275600-7babb285-cae8-4953-95d1-85c4c56bb774.png)

**Comment by zwweber** [comment]
I also received errors while running Tool 15.
![image](https://user-images.githubusercontent.com/87150927/130128862-0f73a61f-95ce-45e8-b323-40539641bd9a.png)
A GIS Specialist helped me by re-running scripts in the "LibraryInstall.R" as described in Appendix D.  I had run the 2 scripts (on line 20 and 23-24) prior to tool testing.  But the GIS Specialist ran more scripts following my Tool 15 errors.  Following his help, I did get Tool 15 to run and it generated 026 and letter.

The R scripts are cumbersome and the instructions are somewhat difficult (for the layperson like me).  My interpretation was that only 2 lines of script needed to be run.  Apparently more lines needed to be run though???

**Comment by zwweber** [comment]
forgot to leave my email address: zach.weber@usda.gov

**Comment by ALWAEW** [comment]
For the second Round of testing, in a row, I am unable to produce any forms or letters.  I am getting the same error, as everyone has listed above, in this thread.
