### ISSUE TITLE
Test 2 Tool B 08. Validate Sampling Units

### ISSUE THREAD

**Issue by DeePederson** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#56]
[ga267_t0000973_2021_08_log.txt](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/files/6970829/ga267_t0000973_2021_08_log.txt)

Validation failed. Reason given was duplicate SU identifier entries, but there are no duplicates.
![image](https://user-images.githubusercontent.com/86242670/129089221-df82ef77-4204-4d73-8dd8-e12356413b27.png)

I am going to re-label my sampling units without the "a" or "b" and see if that works.

**Comment by DeePederson** [comment]
labelling the SUs 1-7 ran with no errors. Must be something related to the letters.

**Comment by CEM-NRCS** [comment]
Moved the letter to a separate column/field. User guide updated with new instructions.
