### ISSUE TITLE
Tool A06 Export Reference Maps - Hillshade

### ISSUE THREAD

**Issue by MelHann213** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#57]
I want to suggest the creation of a colorized Hillshade DEM map without the contours displayed. The existing map with contours overlaying the hillshade 
![ReferenceMap_hillshade](https://user-images.githubusercontent.com/43419575/129383806-ee69409a-9b62-4b5d-9130-4c87dbee9c6d.PNG)
is not as legible and useful.

**Comment by CEM-NRCS** [comment]
Reduce the contour interval in this scenario and/or manually create exactly the desired map with manual layout and export steps.
