### ISSUE TITLE
Tool A05 Reference - Soils symbology

### ISSUE THREAD

**Issue by MelHann213** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#58]
First, Soil pop-up information is awesome!
Black soil lines and mapunit symbols are somewhat difficult to read...maybe the standard orange or white or halo could help.
![ReferenceMap_soils](https://user-images.githubusercontent.com/43419575/129384371-3d07da24-6a1c-4783-993a-e1ab713defdf.PNG)

**Comment by CEM-NRCS** [comment]
Layer can be modified after it has been added to the map either manually or by importing a saved layer file or applying a stored style. Unless re-running the SSURGO download tool, the layer will not be removed/re-added and should retain the revised colors you set.
