### ISSUE TITLE
PLSS point

### ISSUE THREAD

**Issue by japitts8816** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#59]
This is probably a PICNIC issue, but when I was creating the CWD Determinations Map *pdf, there was an option to put in the PLSS point.  I attempted it and got this error message.  Again, it was probably a PICNIC issue.  But thought I'd bring it to your attention just the same.  
![PLSS point error message](https://user-images.githubusercontent.com/63659670/129762116-05f470fa-aab3-4c51-b1af-60e98369cca0.jpg)

**Comment by CEM-NRCS** [comment]
Refined instructions in final release documentation to clarify the use of the PLSS point function. Also populated the embedded Help tips in the tools.
