### ISSUE TITLE
Test 2 Create Project failed to create project spatial reference missing

### ISSUE THREAD

**Issue by MaryEllenCannon** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#60]
Hello I figure I missed something on set up.

 
[Messages_FailedToCreateProjectSpatialReferenceMissing.docx](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/files/7017661/Messages_FailedToCreateProjectSpatialReferenceMissing.docx)
![SnipandSketchFailedOnCreateProjectTest2_Aug19_2021](https://user-images.githubusercontent.com/89223822/130143023-41702e05-4be1-4539-8ba4-87691fe05459.jpg)

**Comment by CEM-NRCS** [comment]
Error messaging added to explain missing spatial references. Documentation updated for state administrators and users about setting a map frame's spatial reference for the tools.
