### ISSUE TITLE
TEST 3 - Task B8 

### ISSUE THREAD

**Issue by DGehring-KY** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#65]
I can get through all the tasks up until B8, then there is no option to advance forward.  Both the SKIP and NEXT buttons are greyed out. I have no idea what needs to happen here to move forward.  I have tried turning things on and off and nothing seems to happen.

**Comment by CEM-NRCS** [comment]
Tasks were dropped from the final release.
