### ISSUE TITLE
NWI map not functioning - broken source link

### ISSUE THREAD

**Issue by DGehring-KY** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#66]
Once I became stuck at Task B8, I noticed that the NWI map is not functioning.  The source has changed for whatever reason and the link is broken.   I am logged into the testing portal as required in Task A3. This seems to cause the NWI map to no longer have a link to it.  The source on the NWI maps is going to the portal https://gis.sc.egov.usda.gov/data/rest/services/wetlands/national_wetland_inventory/FeatureServer  
Not sure why this is not working.

**Comment by CEM-NRCS** [comment]
NWI process went through several revisions during final development passes.  A new procedure now exists in the final release relating to NWI. Tasks were also dropped in the final release.
