### ISSUE TITLE
01. Create Forms and Letters error

### ISSUE THREAD

**Issue by gahisu** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#72]
Using tool Version 1.0.6 (6/23/2022; Production Release), with clean install of R, and WC Tool.
Error: argument is of length zero.

![Create Forms and Letters error](https://user-images.githubusercontent.com/66690345/176438646-fbfa1c14-34cd-4bf3-b550-9246cd986614.png)

**Comment by CEM-NRCS** [comment]
Tool version 1.1.0 made updates to the WC_Report_Tool.r file. Recommend updating to tool 1.1.0 as well as installing new versions of R and RStudio as detailed in the updated User Guide under the "Install Base Software" section. Also recommend installing Java (32-bit or 64-bit according to the architecture type of the computer in question), and following the updated instructions for "Configure R" in the updated User guide to resolve this error.
