### ISSUE TITLE
Rtool required to complete LibraryInstall.r

### ISSUE THREAD

**Issue by J-Hellums** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#73]
On execution of LibraryInstall.r line 34 the warning shown below appears and fails to finish the 'arcgisbinding'. Rtools is located in Software Center. Suggest adding this step to the installation instructions lesson 2 after installing Rstudio. 

WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

jason.hellums@usda.gov

**Comment by CEM-NRCS** [comment]
Rtools version required to build warning message is not applicable to functions.  LibraryInstall.r file has been updated in version 1.1.0 to mitigate installation issues and documentation guides were updated for clarity.

If arcgisbinding package fails to install, disconnect from VPN and try again. The repo response sometimes has poor latency in general, particularly over VPN.

**Comment by CEM-NRCS** [comment]
Seeing some issues with various R installations to register a particular .dll.  Re-opening.

**Comment by CEM-NRCS** [comment]
Tools are moving to a Python based implementation for forms and letters to address this type of issue, and others, from R. Version 2.0.0 Dev is posted and resolves this problem.
