### ISSUE TITLE
Could not find function "read.xlsx.

### ISSUE THREAD

**Issue by J-Hellums** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#74]
could not complete 01. Create Forms and Letters. Re ran LibraryInstall.r with the same result. Noted the 403 Forbidden and tried to open  'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.rds' the following message from UC Berkeley displayed stating the CRAN mirror restricted to UC Berkeley. There is a link to other CRAN mirrors.  

![image](https://user-images.githubusercontent.com/91282935/182921049-066a78a1-32e5-455e-a977-d3ad672c45b3.png)

01. Create Forms and Letters
=====================
Parameters

Select the Site CWD layer from the dropdown     Site_CWD
Include PJW Statement on CPA 026 WC form?     Yes
Create an NRCS CPA 028 for Previous Determinations on the Tract?     No
Select Administering NRCS Office     Decatur Service Center
Select Administering FSA Office     Allen County FSA
(Auto-populates) Path to the Admin Info Excel Table     C:/Determinations/il191_t0004199_2022_07/Admin_Table.xlsx
(Auto-populates) Path to the CLU_CWD_026 Excel Table     C:/Determinations/il191_t0004199_2022_07/Wetlands/CLU_CWD_026.xlsx
(Auto-populates) Path to the Project Wetlands Folder     C:/Determinations/il191_t0004199_2022_07/Wetlands
(Optionally Auto-populates) Path to the CLU_CWD_028 Excel Table     
(Auto-populates) Path to the install directory     C:/GIS_Tools/NRCS_Wetland_Tools_Pro/SUPPORT
(Optional) Consolidate form rows by wetland label?     
=====================
Environments

Scratch Workspace     C:\GIS_Tools\NRCS_Wetland_Tools_Pro\SUPPORT\SCRATCH.gdb
Current Workspace     C:\GIS_Tools\NRCS_Wetland_Tools_Pro\SUPPORT\SCRATCH.gdb
=====================
Messages

Start Time: Thursday, August 4, 2022 12:50:58 PM
Installing package into 'C:/Users/Jason.Hellums/Documents/R/win-library/4.2'
(as 'lib' is unspecified)
cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/src/contrib:
  cannot open URL 'http://cran.cnr.Berkeley.edu/src/contrib/PACKAGES'package 'xlsx' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packagescannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.2/PACKAGES.rds': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.2/PACKAGES.gz': HTTP status was '403 Forbidden'cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.2/PACKAGES': HTTP status was '403 Forbidden'unable to access index for repository http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.2:
  cannot open URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/4.2/PACKAGES'
Loading required package: xlsx
package 'xlsx' was built under R version 4.2.1
Error: package or namespace load failed for 'xlsx':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: JAVA_HOME cannot be determined from the Registry
Loading required package: rmarkdown
package 'rmarkdown' was built under R version 4.2.1
Loading required package: knitr
package 'knitr' was built under R version 4.2.1
Loading required package: flextable
package 'flextable' was built under R version 4.2.1
Loading required package: textreadr
package 'textreadr' was built under R version 4.2.1
Loading required package: dbplyr
package 'dbplyr' was built under R version 4.2.1
[1] "Input parameter names: `Select_Site_CWD`, `PJW_Statement`, `Create_028`, `NRCS_Office`, `FSA_Office`, `Admin_Excel_Path`, `CLU_CWD_026_Excel_Path`, `CLU_CWD_028_Excel_Path`, `Path_to_the_install_directory`, `Consolidate`"
[1] "Output parameter names: `Wetlands_Folder_Path`"
processing file: WC_CustomerLetter.Rmd

  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |..........                                                            |  14%
  ordinary text without R code

  |                                                                            
  |....................                                                  |  29%
label: setup (with options) 
List of 2
 $ include: logi FALSE
 $ echo   : logi FALSE
Quitting from lines 11-55 (WC_CustomerLetter.Rmd) 
could not find function "read.xlsx"
Failed to execute (CreateFormsAndLetters).
Failed at Thursday, August 4, 2022 12:51:07 PM (Elapsed Time: 9.18 seconds)

**Comment by CEM-NRCS** [comment]
CRAN mirror for the xlsx package appears to be either online or moved and working when testing for this issue. Suggest downloading version 1.1.0 of the wetland tools and trying the updated LibraryInstall.R file. Also suggest disabling VPN (with ArcGIS Pro closed) when trying to run the install packages command within LibraryInstall.R in RStudio.

**Comment by CEM-NRCS** [comment]
Also, you might need to confirm your system has Java. Java can be installed from Software Center, per the updated user guide posted with tool version 1.1.0.  Be sure to grab the 32-bit or 64-bit version that is appropriate to your system's type (viewable in About Your PC in the Windows Task Bar search window).

**Comment by CEM-NRCS** [comment]
Now seeing some issues with a DLL file in the R installation potentially not registering properly during install.

**Comment by EM-NRCS** [comment]
Change your default Primary CRAN repository to Global (CDN) - RStudio by opening RStudio click in Tools menu, select Global Options - Packages, click the Change button and select Global (CDN) - RStudio then click Apply and OK

**Comment by CEM-NRCS** [comment]
Tools are moving to a Python based implementation for forms and letters to address this type of issue, and others, from R.  Version 2.0.0 Dev is posted and resolves this problem.
