### ISSUE TITLE
textreadr (required package for tool)

### ISSUE THREAD

**Issue by jacobisleib** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#75]
I was unable to install the textreadr package using the LibraryInstall.R script that was provided. (My R version is 4.2.1)
I found that running the following script successfully installed textreadr:

if (!require("pacman")) install.packages("pacman")
pacman::p_load_gh("trinker/textreadr")

**Comment by EM-NRCS** [comment]
The following code is intended to install the library from the archive site:

install.packages("devtools")
require(devtools)
install_version("textreadr", version = "1.2.0", repos = "https://cran.r-project.org/")
