### ISSUE TITLE
Create Elevation Derivatives fails with NRCS Bare Earth 1m DEM web service

### ISSUE THREAD

**Issue by ryan-nagelkirk** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#77]
In 10-12 counties in eastern Texas, the Create Elevation Derivatives tool fails when using the bare_earth_1m web service as the DEM input. Locally saved DEMs run successfully in the tool. The error states no spatial reference exists, however all layers involved have spatial references. The error also says the table already exists, but that appears to be a generic error message which was a dead end when it came to online troubleshooting. The tool has worked previously using the we service and this issue did not start until Dec. 8th. The user has been signed into both GIS-States and Geoportal in ArcGIS Pro. The same error occurred using these three elevation web services on Geoportal: bare_earth_1m, bare_earth_1m_usgs and 1M Bare Earth. The CLU had complete DEM coverage. We've been troubleshooting since Dec. 8 with no luck. 

Submitted by Ryan Nagelkirk
User: Brenton Fetting

**Comment by ryan-nagelkirk** [comment]
![Screenshot](https://user-images.githubusercontent.com/88210613/207105850-4323c414-1daa-45b4-81f2-96786c34f7bb.png)
![ErrorMessage](https://user-images.githubusercontent.com/88210613/207105901-b500478b-8fb2-468f-9324-172d679a3446.png)

**Comment by CEM-NRCS** [comment]
The only reliable resolution we've found to "table already exists" errors is to delete the tool folder installation (NRCS_Wetland_Tools_Pro) from the affected system and then download/unzip a fresh version of the tool on that system. It is also advised that if the user has custom personal templates for the tool (in My Templates), that they either transfer them from the old folder, through an intermediate during the delete/replace, or that they remake new personal templates from those provided by the State Tool Administrator, or from the default Blank Templates if the user in question _is_ the State Tool Administrator.
