### ISSUE TITLE
Letter Template - Set Date

### ISSUE THREAD

**Issue by ryan-nagelkirk** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#80]
In the new version of the WC Tool (v2.0.0), the determination letter has a date at the end of the first paragraph that is set in the text, and maybe needs to change automatically. Clarification on this would be helpful for training purposes, if nothing else. 

![image](https://user-images.githubusercontent.com/88210613/221930617-fdb096c8-0325-4804-9afb-e6e03e85ad16.png)

Thank you!

**Comment by CEM-NRCS** [comment]
Automatic date enabled in latest version posted to GIT as of 3/22/2023
