### ISSUE TITLE
FSA County Committee Auto-population 

### ISSUE THREAD

**Issue by ryan-nagelkirk** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#81]
On page 3 of the WC_Letter_Template.docx (Image 1 in attached .docx), the FSA County Committee name is populating incorrectly. 

As an example, in the attached document, Image 2 shows the county options for the FSA office located in Nacogdoches. This office services 5 counties. As it is, the tool auto-populates the first county (Angelina) regardless of the actual county the user is working in. This happens for all offices that service multiple counties: the first county in the table is used to populate the letter. 

A few thoughts are to have the user select the correct county from a drop down in the function, or pull the name from other tool input fields. Or provide a warning so the user knows to edit the letter as needed. Please contact us for any needed clarification. Thank you!
[County_Committee_20230301.docx](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/files/10865395/County_Committee_20230301.docx)

**Comment by CEM-NRCS** [comment]
Will review with the developers. May need to add an FSA County option to tool parameters to sync up with the table.

**Comment by CEM-NRCS** [comment]
Updated requirements for Create Forms and Letters tool in both Training and standard toolboxes -
Add a user input parameter for "Select FSA County Committee County".
Set this new parameter as parameter 5. Move down the Optional consolidate parameter to parameter 6.
The new parameter for "Select FSA County Committee County" should be of String type.
Validation should be updated to read the fsa_table to pull the FSACounty column to build the Value List for the parameter, e.g. - 
self.params[5].filter.list = [str(val) for val in sorted(set(row[0] for row in arcpy.da.SearchCursor(fsa_table, 'FSACounty')))]

Also update the updateMessages for old parameter 5 to now be parameter 6, e.g. (change [5].value to [6].value in after adding the new parameter - 
if self.params[5].value == 1:
                if not arcpy.Exists(clu_cwd_026_alt_table_path):
                    self.params[0].setErrorMessage("The project's 026 Alt Table does not exist or was moved. Please verify that the correct Site CWD layer was chosen, or close this tool and re-run Create CWD Mapping Layers.")

Do not add any new validation for the new parameter.

**Comment by dylan-harwell-usda** [comment]
PR: https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/pull/90
