### ISSUE TITLE
Image Service Tile Boundaries Appearing in Exported Reference Maps

### ISSUE THREAD

**Issue by ryan-nagelkirk** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#83]
When using the NAIP 2022 image service or the NHAP image service, image tiles appear in the maps outputted from B. Reference Data > 03. [Optional] Export Reference Maps. 

We tried making the image service unselectable and we made sure Display Footprints in Properties was turned off. Still, the tile boundary displayed. The tiles do not display in PDF maps created using the normal Share > Export Layout workflow. This suggested there might be something set differently in the Export Reference Maps function/tool. 

The issue does not occur when using the normal World Imagery Basemap. However, the 2022 NAIP imagery preferable because it is more recent. 

Attached are examples of the maps created using the following workflows:

1)	WC_Tool_Export_NHAP.pdf: Reference maps exported using WC Tool step B.03, (NHAP image)
2)	WC_Tool_Export_NAIP2022.pdf: Reference maps exported using WC Tool step B.03, (NAIP 2022 image)
3)	WC_Tool_Export_WorldImageryBasemap.pdf: Reference maps exported using WC Tool step B.03, (World Imagery Basemap)
4)	ArcPro_Export_NHAP.pdf: Site map exported using ArcPro Export Map function in Share Tab (NHAP image)

Also attached is a Word document with a screenshot of the setup in Pro. 

The NAIP and NHAP layers we are using is below:
https://services.apfo.usda.gov/arcgis/rest/services/NAIP/USDA_CONUS_PRIME/ImageServer
https://nrcsgeoservices.sc.egov.usda.gov/arcgis/rest/services/ortho_imagery/nhap_All/ImageServer

[ArcPro_Export_NHAP.pdf](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/files/10884297/ArcPro_Export_NHAP.pdf)
[ImageTile.docx](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/files/10884298/ImageTile.docx)
[WC Tool_Export_NAIP2022.pdf](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/files/10884299/WC.Tool_Export_NAIP2022.pdf)
[WC Tool_Export_NHAP.pdf](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/files/10884300/WC.Tool_Export_NHAP.pdf)
[WC Tool_Export_World Imagery Basemap.pdf](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/files/10884302/WC.Tool_Export_World.Imagery.Basemap.pdf)

**Comment by AC0192021** [comment]
Yes, Iowa reported this in the past as well.  CIR imagery services return red lines.

**Comment by CEM-NRCS** [comment]
It appears that changing the export PDF command option _layers_attributes_ to be "LAYERS_ONLY" should resolve this. Tested and now planning to implement in an upcoming merge.
