### ISSUE TITLE
Site_Drainage_Lines - - White Symbology Not Visible in Legend

### ISSUE THREAD

**Issue by AC0192021** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#88]
WC Tool Version 2.0: Site_Drainage_Lines symbology is not visible in legend and output PDF due to Layout View canvas white background and the symbology itself is white.

  
![Site_Drainage_Lines_Legend Symbology Not Visible in Layout View nor PDF](https://user-images.githubusercontent.com/87500821/227260071-308e3084-f5ae-4c85-b443-a7515b376820.PNG)
![Site_Drainage_Lines_Contents Pane](https://user-images.githubusercontent.com/87500821/227260117-b0c50c13-2b72-4501-8a31-bb3b9e659b1b.PNG)

**Comment by dylan-harwell-usda** [comment]
@CEM-NRCS Thoughts on this one: we could give the legend a background that isn't white or black, light gray? Or use some other color besides white for those particular drainage lines?

**Comment by CEM-NRCS** [comment]
@dylan-harwell-usda @AC0192021  OK. I'll take the suggestion of updating colors and/or symbols for drainage to Jason and David for final review and approval before we begin this.

**Comment by CEM-NRCS** [comment]
@dylan-harwell-usda @AC0192021 I reviewed this issue with David Manthei this morning. He has agreed to an update to the existing symbols for style consistency and visibility. Dylan - I'll generate a new layer file and replace it in the repo.

**Comment by dylan-harwell-usda** [comment]
Chris pushed this symbology change in this commit: https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/commit/d2a6353ec8fa4e92d8a34c6224c9cd3890957de6
